services:
  builder:
    build: .
    platform: linux/amd64
    volumes:
      - ./:/src:ro
      - ./output:/output
    cap_add:
      - SYS_ADMIN
      - MKNOD
      - SYS_CHROOT
    security_opt:
      - apparmor:unconfined
    command: docker-entrypoint.sh
